### ISSUE TITLE
Example is broken?

### ISSUE THREAD

**Issue by ignas2526** [igorkamyshev/nanoption#1]
Looking at the example, I think that variables are named incorrectly. Why it is not like this?
```
function getJwtToken(executionContext) {
  const jwtToken = Option.of(executionContext)
    .map(httpMod => context.switchToHttp()) // context can have no http mod (e.g. WebSocket)
    .map(request => httpMod.getRequest())   // context can have no http request
    .map(headers => request.headers)        // request can have no headers
    .map(jwtAuth => headers.authorizarion)  // headers can have no auth header
    .map(jwtToken => jwtAuth.split(' ‘)[1])  // auth header can contain only one part
    .getOrElse(‘’)

  return jwtToken
}
```

**Comment by igorkamyshev** [comment]
Hi. Because `map` accept callback, that function will apply to value. Your code is not correct JS, you try to use variables in one function from another.

In original example we sequentially transform executionContext. In first map we make `httpMode from context`.

I will try to clarify example next week.
